/** Pinpoint email template names — must match templates in AWS Pinpoint (legacy). */
export enum TemplateName {
  YourTripExtensionIsConfirmedGuest = 'YourTripExtensionIsConfirmedGuest',
  YouConfirmedATripExtension = 'YouConfirmedATripExtension',
  YouRequestedATripExtension = 'YouRequestedATripExtension',
  TripExtensionRequestHost = 'TripExtensionRequestHost',
  YoureCheckedInGuest = 'YoureCheckedInGuest',
  GuestHasCheckedInUsingYourRide = 'GuestHasCheckedInUsingYourRide',
  YoureCheckedOutGuest = 'YoureCheckedOutGuest',
  GuestCheckedOutOfYourRide = 'GuestCheckedOutOfYourRide',
  WriteAReviewForGuestName = 'WriteAReviewForGuestName',
  WriteAReviewGuest = 'WriteAReviewGuest',
  HostWroteYouAReview = 'HostWroteYouAReview',
  GuestNameWroteAReview = 'GuestNameWroteAReview',
  YouSentAReservationRequest = 'YouSentAReservationRequest',
  BookingRequest = 'BookingRequest',
  ConfirmedBookingRequestHost = 'ConfirmedBookingRequestHost',
  BookingRequestConfirmedGuest = 'BookingRequestConfirmedGuest',
  YourBookingRequestWasDenied = 'YourBookingRequestWasDenied',
  YouDeniedABookingRequest = 'YouDeniedABookingRequest',
  LicenseApproved = 'LicenseApproved',
  LicenseDenied = 'LicenseDenied',
  VerifyEmail = 'VerifyEmail',
  Welcome = 'Welcome',
  ListingApproved = 'ListingApproved',
  ListingDenied = 'ListingDenied',
  AccountActivityNewPaymentMethod = 'AccountActivityNewPaymentMethod',
  PasswordRecovery = 'PasswordRecovery',
  YourTripIsEndingSoonGuest = 'YourTripIsEndingSoonGuest',
  YourTripIsEndingSoonHost = 'YourTripIsEndingSoonHost',
  YourTripIsBeginningSoonGuest = 'YourTripIsBeginningSoonGuest',
  TripBeginningSoonHost = 'TripBeginningSoonHost',
  NewMessageFromHost = 'NewMessageFromHost',
  NewMessageFromGuest = 'NewMessageFromGuest',
  YouHaveDeniedATripExtenison = 'YouHaveDeniedATripExtenison',
}
